### PR TITLE
Use gcc crate instead of homegrown hack

### PR DESCRIPTION
**Pull request by polachok**

### CODE REVIEW

**Comment by mrmonday** [comment]
Hi there!

Thank you for your work. A couple of points:
- Could you use spaces instead of tabs please?
- This change removes the -Dstatic= -Dinline= hack, which means that the symbols are not exported, so linking will fail

Unrelatedly, we should really get Travis set up so this gets tested automatically.

**Comment by polachok** [comment]
I pushed an update and added a little test to see if it links.

**Comment by polachok** [comment]
I'll create a PR for travis when this one is merged (see https://github.com/polachok/netmap_sys/pull/2/files)

**Comment by mrmonday** [comment]
I'd actually really appreciate it if you could make the pull request for Travis now, since you've done the work! It would mean that this one can be tested properly before merging, which would be great.

Before you do that, could you add:

``` yaml
cache:
    directories:
        - $HOME/.cargo
rust:
    - stable
    - beta
    - nightly
notifications:
    irc:
        channels:
            - "chat.freenode.net#libpnet"
        use_notice: true
```

In there? Thanks!

**Comment by mrmonday** [comment]
Great work, thanks!

**Pull request merged**
